In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn . linear_model import Lasso
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
X = data
y = target
fit = Lasso(alpha=500).fit(X, y)  # alpha = penalty
y_pred = fit.predict(X)
coef = fit.coef_
sel = (coef != 0)
XNames = raw_df.columns[:data.shape[1]]
print(XNames)
print(np.round(coef, 2))
#print(XNames[sel])
print(np.round(coef[sel], 2))

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')
[-0.    0.   -0.    0.   -0.    0.   -0.    0.   -0.   -0.01 -0.    0.
 -0.  ]
[-0.01]


In [12]:
# lasso with standardization
muhat = np . mean (X , axis = 0)
stdhat = np . std (X , axis = 0)
Xtilde = (X - muhat )/ stdhat # standardize
y = target
fit = Lasso ( alpha = 1.3). fit ( Xtilde , y )
yhat = fit . predict ( Xtilde ) # Q : Why OK ?
coef = fit . coef_
sel = ( coef != 0)
XNames = raw_df.columns[:data.shape[1]]
#print ( XNames [ sel ])
print ( np . round ( coef [ sel ] ,2)) # in std . dev . s
coef_orig = coef / stdhat
print ( np . round ( coef_orig [ sel ] ,2)) # original

[ 2.54 -1.16 -3.49]
[ 3.61 -0.54 -0.49]


In [ ]:
# BRT rule
from scipy.stats import norm
sigma = np . std ( y )
(n , p ) = X . shape
Xscale = np . max ( np . mean (( X ** 2) , axis = 0)) ** 0.5
c = 1.1; alpha = 0.05
lamb = c * sigma * norm.ppf (1 - alpha /(2* p ))
lamb *= Xscale / np.sqrt ( n )
# BRT as stated - -^ & upon normalizing --v
lamb1 = c * sigma * norm.ppf (1 - alpha /(2* p ))/ np.sqrt ( n )
print (lamb) # the lambda here is blown up bc regressoors are not measured on the same scale
print (lamb1) # here the regressors are standardized
# Note : Dividing by 2 ( Python Lasso definition ) 24 / 29


573.5058823812358
1.2987144409659397


In [ ]:
# cross validation
from sklearn.linear_model import LassoCV
fitCV = LassoCV(cv=5).fit(Xtilde,y)
coef_ = fitCV.coef_
sel = (coef_ !=0)
print(np.round(coef_[sel],2))

from sklearn.model_selection import KFold


[-0.47  0.5  -0.07  0.64 -1.31  2.91 -2.03  0.37 -0.16 -1.85  0.71 -3.72]


: 

In [ ]:
# 