In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Matplotlib is building the font cache; this may take a moment.


In [ ]:
# leger lidt rundt med matricer
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])
B = np.array([[5, 6, 9],
              [6, 7, 11],
              [7, 8, 13]])

print('A er en', A.shape, 'matrice med', A.ndim, 'dimensioner og dermed', A.size, 'elementer')

# koder OLS op fra bunden
X = A
y = B
# estimatoren er defineret som ((X'X)^(-1))X'y 
#beta = np.linalg.inv(X.T@X)@X.T@y
# skal faktisk bruge pseudo-inversen fordi matrix A ikke har fuld rank
beta = np.linalg.pinv(X.T @ X) @ X.T @ y

# bruger beta til at forudsige y


y_hat = X @ beta

print(beta)

A er en (3, 3) matrice med 2 dimensioner og dermed 9 elementer
[[0.9047619  1.04761905 1.66666667]
 [0.9047619  1.04761905 1.66666667]
 [0.9047619  1.04761905 1.66666667]]
